### ISSUE TITLE
NullPointer Exeption when pressing back 

### ISSUE THREAD

**Issue by michaelsam94** [PandoraMedia/BottomNavigator#21]
kotlin.KotlinNullPointerException
        at com.pandora.bottomnavigator.BottomNavigator.pop(BottomNavigator.kt:213)
        at HomeFragment$onCreate$1.handleOnBackPressed(HomeFragment.kt:29)
        at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.java:192)
        at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:314)
        at android.app.Activity.onKeyUp(Activity.java:2488)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2685)
        at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:137)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2317)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4131)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4093)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3824)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3985)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2261)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1882)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1873)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2238)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:331)
        at android.os.Looper.loop(Looper.java:218)
        at android.app.ActivityThread.main(ActivityThread.java:5526)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

**Comment by guelo** [comment]
Thanks for the stacktrace, do you have steps to reproduce this crash?

**Comment by michaelsam94** [comment]
this is sample project to reproduce issue https://github.com/michaelsam94/BottomNavigatorIssue
this app follow single activity approach

**Comment by guelo** [comment]
Thanks so much for the project. I'm running it and clicking around in the app but I haven't been able to reproduce the crash. Any idea how to make it happen?

**Comment by michaelsam94** [comment]
first open home and navigate through bottom taps and after that press back until you go to login fragment and go to home fragment again and press back

**Comment by guelo** [comment]
Finally got around to working on this, the bug is fixed in release 1.8. Thanks for the report.

**Comment by michaelsam94** [comment]
You are most welcome thank you for your contribution to open source community
